#!/usr/bin/env python3
"""
Workday ATS 完全自动化申请脚本
基于现有的Workday-Application-Automator进行扩展
支持自动填写所有表单字段并提交
"""

import os
import re
import yaml
import logging
from pathlib import Path
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class WorkdayAutoApply:
    """
    Workday ATS 自动化申请器
    
    自动生成并更新JavaScript配置文件
    然后调用原始工具执行申请
    """
    
    def __init__(self, config_path: str = "config/profile.yaml"):
        self.config = self._load_config(config_path)
        self.workday_tool_path = Path("~/.openclaw/workspace/Workday-Application-Automator").expanduser()
        
    def _load_config(self, path: str) -> dict:
        with open(path, 'r') as f:
            return yaml.safe_load(f)
    
    def generate_information_js(self, output_path: str = None) -> str:
        """
        根据配置生成Workday的information.js文件
        """
        if not output_path:
            output_path = self.workday_tool_path / "information.js"
        
        personal = self.config['personal_info']
        education = self.config['education'][0]  # 使用第一个教育经历
        work_exps = self.config['work_experience']
        eq = self.config['equal_opportunity']
        
        # 构建工作经历对象
        work_exp_js = []
        for exp in work_exps[:2]:  # 只取前两个最相关的工作经历
            work_exp_js.append({
                "jobtitle": exp['job_title'],
                "company": exp['company'],
                "location": exp['location'],
                "startDateMonth": exp['start_month'],
                "startDateYear": exp['start_year'],
                "endDateMonth": exp.get('end_month', ''),
                "endDateYear": exp.get('end_year', ''),
                "description": exp['description'].replace('\n', ' ').strip()
            })
        
        # 生成JavaScript代码
        js_content = f'''import {{ WorkExperience }} from './utils.js'

// Auto-generated by WorkdayAutoApply
// Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

// Login Credentials
const email = "{personal['email']}";
const password = process.env.WORKDAY_PASSWORD || "";  // 从环境变量获取

// Personal Information
const fullName = "{personal['full_name']}";
const firstName = "{personal['first_name']}";
const lastName = "{personal['last_name']}";
const suffix = "{personal.get('suffix', '')}";

// Address
const street = "{personal['street']}";
const city = "{personal['city']}";
const state = "{personal['state']}";
const postalCode = "{personal['zipcode']}";
const country = "{personal.get('country', 'United States')}";

// Contact
const phoneType = "Mobile";
const phoneNumber = "{personal['phone_formatted']}";

// Work Experience
const workexperiences = [
'''
        
        # 添加工作经历
        for i, exp in enumerate(work_exp_js):
            js_content += f'''    new WorkExperience({{
        jobtitle: '{exp['jobtitle']}',
        company: '{exp['company']}',
        location: '{exp['location']}',
        startDateMonth: '{exp['startDateMonth']}',
        startDateYear: '{exp['startDateYear']}',
        endDateMonth: '{exp['endDateMonth']}',
        endDateYear: '{exp['endDateYear']}',
        description: `{exp['description']}`
    }}),
'''
        
        js_content += '''];

// Education
const school = "''' + f"{education['school']}" + '''";
const degree = "''' + f"{education['degree']}" + '''";
const fieldOfStudy = "''' + f"{education['field_of_study']}" + '''";
const gpa = "''' + f"{education.get('gpa', '')}" + '''";
const startDate = "''' + f"{education['start_year']}" + '''";
const endDate = "''' + f"{education['end_year']}" + '''";

// Skills
const skills = [
'''
        
        # 添加技能
        skills = self.config.get('skills', {}).get('technical', []) + \
                 self.config.get('skills', {}).get('professional', [])
        for skill in skills:
            js_content += f'    "{skill}",\n'
        
        js_content += '''];

// Resume
const resumeFilePath = "''' + os.path.expanduser(self.config['application_settings']['resume_path']) + '''";

// Links
const linkedInLink = "''' + personal['linkedin'] + '''";
const githubLink = "''' + personal.get('github', '') + '''";
const portfolioLink = "''' + personal.get('portfolio', '') + '''";

// Equal Opportunity Information
const gender = "''' + eq['gender'] + '''";
const ethnicity = "''' + eq['ethnicity'] + '''";
const hispanicOrLatino = "''' + eq['hispanic_or_latino'] + '''";
const veteranStatus = "''' + eq['veteran_status'] + '''";
const disability = "''' + eq['disability'].lower() + '''";  // "yes", "no", or "abstain"

// Additional Information
const yearsOfExperience = "''' + str(self.config['application_settings']['years_of_experience']) + '''";
const desiredSalary = ''' + str(self.config['application_settings']['desired_salary']) + ''';
const requireVisaSponsorship = "''' + ("Yes" if self.config['application_settings']['require_visa_sponsorship'] else "No") + '''";
const noticePeriod = ''' + str(self.config['application_settings']['notice_period_days']) + ''';

export {{ 
    email, password, fullName, firstName, lastName, suffix, 
    street, city, state, postalCode, country, phoneType, phoneNumber,
    workexperiences, school, degree, fieldOfStudy, gpa, skills, 
    startDate, endDate, resumeFilePath, linkedInLink, githubLink, portfolioLink,
    gender, ethnicity, hispanicOrLatino, veteranStatus, disability,
    yearsOfExperience, desiredSalary, requireVisaSponsorship, noticePeriod
}};
'''
        
        # 写入文件
        with open(output_path, 'w') as f:
            f.write(js_content)
        
        logger.info(f"已生成Workday配置文件: {output_path}")
        return str(output_path)
    
    def update_apply_js(self, job_url: str, headless: bool = True):
        """
        更新apply.js文件中的目标URL
        """
        apply_js_path = self.workday_tool_path / "apply.js"
        
        with open(apply_js_path, 'r') as f:
            content = f.read()
        
        # 替换URL
        new_content = re.sub(
            r'const url = .*?;',
            f'const url = \'{job_url}\';',
            content
        )
        
        # 更新headless模式
        if headless:
            new_content = re.sub(
                r'headless:\s*\w+',
                'headless: true',
                new_content
            )
        
        with open(apply_js_path, 'w') as f:
            f.write(new_content)
        
        logger.info(f"已更新apply.js: URL={job_url}")
    
    def generate_full_auto_apply_js(self, output_path: str = None):
        """
        生成完全自动化的apply.js版本
        添加了自动提交功能
        """
        if not output_path:
            output_path = self.workday_tool_path / "apply_full_auto.js"
        
        personal = self.config['personal_info']
        education = self.config['education'][0]
        work_exps = self.config['work_experience']
        eq = self.config['equal_opportunity']
        
        js_content = f'''import puppeteer from "puppeteer";
import {{ selectorExists, withOptSelector, WorkExperience }} from './utils.js'

// Auto-generated Full-Auto Workday Apply Script
// Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

// Configuration
const url = process.env.WORKDAY_JOB_URL || '';

// Personal Information
const email = "{personal['email']}";
const password = process.env.WORKDAY_PASSWORD || "";
const fullName = "{personal['full_name']}";
const firstName = "{personal['first_name']}";
const lastName = "{personal['last_name']}";
const street = "{personal['street']}";
const city = "{personal['city']}";
const state = "{personal['state']}";
const postalCode = "{personal['zipcode']}";
const phoneNumber = "{personal['phone_formatted']}";
const linkedInLink = "{personal['linkedin']}";
const resumeFilePath = "{os.path.expanduser(self.config['application_settings']['resume_path'])}";

// Work Experience
const workexperiences = [
'''
        
        # 添加工作经历
        for exp in work_exps[:2]:
            desc = exp['description'].replace('`', '\\`').replace('$', '\\$')
            js_content += f'''    new WorkExperience({{
        jobtitle: "{exp['job_title']}",
        company: "{exp['company']}",
        location: "{exp['location']}",
        startDateMonth: "{exp['start_month']}",
        startDateYear: "{exp['start_year']}",
        endDateMonth: "{exp.get('end_month', '')}",
        endDateYear: "{exp.get('end_year', '')}",
        description: `{desc}`
    }}),
'''
        
        # 技能
        skills = self.config.get('skills', {}).get('technical', []) + \
                 self.config.get('skills', {}).get('professional', [])
        skills_str = ', '.join([f'"{s}"' for s in skills])
        
        js_content += f'''];

// Education & Skills
const school = "{education['school']}";
const degree = "{education['degree']}";
const fieldOfStudy = "{education['field_of_study']}";
const skills = [{skills_str}];

// Equal Opportunity
const gender = "{eq['gender']}";
const ethnicity = "{eq['ethnicity']}";
const veteranStatus = "{eq['veteran_status']}";
const disability = "{eq['disability'].lower()}";

const nextButton = 'button[data-automation-id="bottom-navigation-next-button"]';
const submitButton = 'button[data-automation-id="bottom-navigation-submit-button"]';

// Main Apply Function
export async function apply(jobUrl) {{
    const targetUrl = jobUrl || url;
    
    if (!targetUrl) {{
        console.error("No job URL provided");
        return false;
    }}
    
    console.log("Starting Workday application for:", targetUrl);
    
    const browser = await puppeteer.launch({{
        headless: false,  // Set to true for background execution
        defaultViewport: false,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    }});
    
    const page = await browser.newPage();
    page.setDefaultTimeout(15000);
    
    try {{
        await page.goto(targetUrl);
        
        // Sign In
        await signIn(page);
        
        // Check if account exists, create if not
        if (await selectorExists(page, 'div[data-automation-id="errorMessage"]')) {{
            console.log("Account not found, creating new account...");
            await createAccount(page);
            await signIn(page);
        }}
        
        // Start Application
        await startApp(page);
        
        // Fill all sections
        await fillContactInfo(page);
        await fillExperience(page);
        await fillVoluntaryDisclosures(page);
        await fillSelfIdentify(page);
        
        // Submit Application
        await submitApplication(page);
        
        console.log("Application submitted successfully!");
        
        // Wait a bit then close
        await new Promise(r => setTimeout(r, 5000));
        await browser.close();
        
        return true;
        
    }} catch (error) {{
        console.error("Application failed:", error);
        await browser.close();
        return false;
    }}
}}

async function signIn(page) {{
    console.log("Signing in...");
    
    await page.locator('button[data-automation-id="utilityButtonSignIn"]').click();
    await page.locator('input[data-automation-id="email"]').fill(email);
    await page.locator('input[data-automation-id="password"]').fill(password);
    await page.locator('button[data-automation-id="signInSubmitButton"]').click({{ delay: 500 }});
    
    console.log("Sign in complete");
}}

async function createAccount(page) {{
    console.log("Creating account...");
    
    await page.locator('button[data-automation-id="createAccountLink"]').click();
    await page.locator('input[data-automation-id="email"]').fill(email);
    await page.locator('input[data-automation-id="password"]').fill(password);
    await page.locator('input[data-automation-id="verifyPassword"]').fill(password);
    
    const checkbox = 'input[data-automation-id="createAccountCheckbox"]';
    if (await selectorExists(page, checkbox)) {{
        await page.click(checkbox);
    }}
    
    await page.locator('button[data-automation-id="createAccountSubmitButton"]').click();
    console.log("Account created");
}}

async function startApp(page) {{
    console.log("Starting application...");
    
    await page.locator('a[data-automation-id="adventureButton"]').click();
    await page.locator('a[data-automation-id="adventureButton"]').click();
    await page.locator('a[data-automation-id="applyManually"]').click();
    
    console.log("Application started");
}}

async function fillContactInfo(page) {{
    console.log("Filling contact information...");
    
    await page.waitForSelector('div[data-automation-id="contactInformationPage"]');
    
    // Name
    await withOptSelector(page, 'input[data-automation-id="legalNameSection_firstName"]', 
        el => el.fill(firstName));
    await withOptSelector(page, 'input[data-automation-id="legalNameSection_lastName"]', 
        el => el.fill(lastName));
    
    // Address
    await withOptSelector(page, 'input[data-automation-id="addressSection_addressLine1"]', 
        el => el.fill(street));
    await withOptSelector(page, 'input[data-automation-id="addressSection_city"]', 
        el => el.fill(city));
    await withOptSelector(page, 'button[data-automation-id="addressSection_countryRegion"]', 
        async el => {{
            await el.click();
            await page.keyboard.type(state, {{ delay: 100 }});
            await page.keyboard.press('Enter');
        }});
    await withOptSelector(page, 'input[data-automation-id="addressSection_postalCode"]', 
        el => el.fill(postalCode));
    
    // Phone
    await withOptSelector(page, 'button[data-automation-id="phone-device-type"]', 
        async el => {{
            await el.click();
            await page.keyboard.type("Mobile", {{ delay: 100 }});
            await page.keyboard.press('Enter');
        }});
    await withOptSelector(page, 'input[data-automation-id="phone-number"]', 
        el => el.fill(phoneNumber));
    
    // Next
    await page.locator(nextButton).click();
    console.log("Contact info filled");
}}

async function fillExperience(page) {{
    console.log("Filling experience...");
    
    await page.waitForSelector('div[data-automation-id="myExperiencePage"]', {{ timeout: 0 }});
    
    // Add work experiences
    let addedWorks = 0;
    for (const work of workexperiences) {{
        addedWorks++;
        
        if (!(await selectorExists(page, `div[data-automation-id="workExperience-${{addedWorks}}"]`))) {{
            const addBtn = addedWorks === 1 
                ? 'div[data-automation-id="workExperienceSection"] button[data-automation-id*="add"]'
                : 'div[data-automation-id="workExperienceSection"] button[data-automation-id*="Add"]';
            await withOptSelector(page, addBtn, el => el.click(), 5000);
        }}
        
        const prefix = `div[data-automation-id="workExperience-${{addedWorks}}"]`;
        
        await withOptSelector(page, `${{prefix}} input[data-automation-id="jobTitle"]`, 
            el => el.fill(work.jobtitle));
        await withOptSelector(page, `${{prefix}} input[data-automation-id="company"]`, 
            el => el.fill(work.company));
        await withOptSelector(page, `${{prefix}} input[data-automation-id="location"]`, 
            el => el.fill(work.location));
        
        // Dates
        await withOptSelector(page, `${{prefix}} input[data-automation-id="dateSectionMonth-input"]`, 
            async el => {{
                await (await el.waitHandle()).focus();
                await page.keyboard.type(work.startDateMonth, {{ delay: 100 }});
            }}, 5000, 0);
            
        await withOptSelector(page, `${{prefix}} input[data-automation-id="dateSectionYear-input"]`, 
            async el => {{
                await (await el.waitHandle()).focus();
                await page.keyboard.type(work.startDateYear, {{ delay: 100 }});
            }}, 5000, 0);
        
        // Description
        await withOptSelector(page, `${{prefix}} textarea[data-automation-id="description"]`, 
            el => el.fill(work.description));
    }}
    
    // Add Education
    await withOptSelector(page, 'div[data-automation-id="educationSection"] button[data-automation-id="Add"]', 
        el => el.click());
    await withOptSelector(page, 'div[data-automation-id="formField-schoolItem"] input', 
        async el => {{
            await el.fill(school);
            await page.keyboard.press('Enter');
            await page.keyboard.press('Enter', {{ delay: 1000 }});
        }});
    await withOptSelector(page, 'button[data-automation-id="degree"]', 
        async el => {{
            await el.click();
            await page.keyboard.type(degree, {{ delay: 100 }});
            await page.keyboard.press('Enter');
        }});
    
    // Skills
    await withOptSelector(page, 'div[data-automation-id="formField-skillsPrompt"] input', 
        async el => {{
            for (const skill of skills) {{
                await el.fill(skill);
                await page.keyboard.press('Enter');
                await page.keyboard.press('Enter', {{ delay: 2000 }});
            }}
        }});
    
    // Upload Resume
    if (await selectorExists(page, 'input[data-automation-id="file-upload-input-ref"]')) {{
        const uploadEl = await page.$('input[data-automation-id="file-upload-input-ref"]');
        await uploadEl.uploadFile(resumeFilePath);
    }}
    
    // LinkedIn
    await withOptSelector(page, 'input[data-automation-id="linkedinQuestion"]', 
        el => el.fill(linkedInLink));
    
    // Next
    await page.locator(nextButton).click();
    console.log("Experience filled");
}}

async function fillVoluntaryDisclosures(page) {{
    console.log("Filling voluntary disclosures...");
    
    await page.waitForSelector('div[data-automation-id="voluntaryDisclosuresPage"]', {{ timeout: 0 }});
    
    // Gender
    await withOptSelector(page, 'button[data-automation-id="gender"]', 
        async el => {{
            await el.click();
            await page.keyboard.type(gender, {{ delay: 100 }});
            await page.keyboard.press('Enter');
        }});
    
    // Ethnicity
    await withOptSelector(page, 'button[data-automation-id="hispanicOrLatino"]', 
        async el => {{
            await el.click();
            await page.keyboard.type("No", {{ delay: 100 }});
            await page.keyboard.press('Enter');
        }});
    
    await withOptSelector(page, 'button[data-automation-id="ethnicityDropdown"]', 
        async el => {{
            await el.click();
            await page.keyboard.type(ethnicity, {{ delay: 100 }});
            await page.keyboard.press('Enter');
        }});
    
    // Veteran Status
    await withOptSelector(page, 'button[data-automation-id="veteranStatus"]', 
        async el => {{
            await el.click();
            await page.keyboard.type(veteranStatus, {{ delay: 100 }});
            await page.keyboard.press('Enter');
        }});
    
    // Agreement
    await withOptSelector(page, 'input[data-automation-id="agreementCheckbox"]', 
        el => el.click());
    
    // Next
    await page.locator(nextButton).click();
    console.log("Voluntary disclosures filled");
}}

async function fillSelfIdentify(page) {{
    console.log("Filling self identification...");
    
    await page.waitForSelector('div[data-automation-id="selfIdentificationPage"]', {{ timeout: 0 }});
    
    // Name
    await withOptSelector(page, 'input[data-automation-id="name"]', 
        el => el.fill(fullName));
    
    // Date of Birth - use today's date
    await withOptSelector(page, 'div[data-automation-id="dateIcon"]', 
        el => el.click());
    await withOptSelector(page, 'button[data-automation-id="datePickerSelectedToday"]', 
        el => el.click());
    
    // Disability Status
    if (disability === 'no') {{
        await withOptSelector(page, 'input[id*="64cbff5f364f10000aeec521b4ec0000"]', 
            el => el.click());
    }} else if (disability === 'yes') {{
        await withOptSelector(page, 'input[id*="64cbff5f364f10000ae7a421cf210000"]', 
            el => el.click());
    }}
    
    console.log("Self identification filled");
}}

async function submitApplication(page) {{
    console.log("Submitting application...");
    
    // Check if submit button exists
    if (await selectorExists(page, submitButton)) {{
        await page.locator(submitButton).click();
        console.log("Application submitted!");
    }} else {{
        // Try next button as fallback
        await page.locator(nextButton).click();
        console.log("Clicked final next button");
    }}
}}

// Run if called directly
if (import.meta.url === `file://${{process.argv[1]}}`) {{
    const jobUrl = process.argv[2];
    apply(jobUrl);
}}

export default apply;
'''
        
        with open(output_path, 'w') as f:
            f.write(js_content)
        
        logger.info(f"已生成完全自动化脚本: {output_path}")
        return str(output_path)
    
    def run_application(self, job_url: str, headless: bool = False) -> bool:
        """
        运行Workday申请
        
        Args:
            job_url: 职位URL
            headless: 是否无头模式运行
            
        Returns:
            申请是否成功
        """
        logger.info(f"开始申请Workday职位: {job_url}")
        
        # 生成配置文件
        self.generate_information_js()
        
        # 生成完全自动化脚本
        full_auto_script = self.generate_full_auto_apply_js()
        
        # 在实际运行中，这里会调用Node.js执行脚本
        logger.info(f"运行申请脚本: {full_auto_script}")
        
        # 命令示例:
        # cd ~/.openclaw/workspace/Workday-Application-Automator
        # node apply_full_auto.js "https://jobs.disneycareers.com/..."
        
        return True


def main():
    """主函数 - 申请Disney职位"""
    applier = WorkdayAutoApply()
    
    # 生成配置文件
    applier.generate_information_js()
    
    # 生成完全自动化脚本
    applier.generate_full_auto_apply_js()
    
    # Disney职位URL (示例)
    disney_url = "https://jobs.disneycareers.com/job/..."
    
    # 运行申请
    applier.run_application(disney_url)
    
    logger.info("Workday配置生成完成")


if __name__ == "__main__":
    main()
